### ISSUE TITLE
Update Event Section

### ISSUE THREAD

**Issue by lornajaneteam** [lornajaneteam/activenationday#23]
deactivate the Find or Register an Event section as registrations are not yet open (find an event and create an event buttons can be changed to coming soon)

**Comment by aanomm** [comment]
Sorry I'm not sure I was aware this was required and not complete. I'll action it ASAP.

**Deactivating Find/Register Events Section**
Deactivating this section is super-simple — in fact deactivating it is the fastest, easiest option — however doing so  slightly impacts the page flow in a few ways...

- All sections are relatively numbered (1., 2., 3., and 4.)
- These numbers are actually images
- The numbers would then start at 2. ( 1. would be missing)
- So I can change the images accordingly to suit the new sections (if 'Find/Register Events' is deactivated)
- Still, this approach means anyone who views the site/page before the add new event section is re-added won't know there is something else they can do in the future. If there is traffic viewing it then perhaps there is another option...

**An Alternate Option?**
The other option could be to leave the 'Find/Register Events' section in and temporarily modify the text in the section ... 
- Modify the text to suggest this feature is coming soon
- Deactivate the buttons (change the colour to light grey and make then un-clickabe)
- This leaves the section in place as a placeholder

**Comment by lornajaneteam** [comment]
The Alternate option is what I was after thanks.

If you could also remove all the events from last year that would be great.

**Comment by aanomm** [comment]
- [x] Temporarily remove Event buttons from Homepage
- [x] I will open a separate ToDo for the Event Removal as the connection between the website and event database is delicate and "Remove" will need some clarification
